version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx_bank
    ports: ['80:80']
    volumes:
      - ./volumes/gateway.nginx:/etc/nginx/conf.d/conf.nginx
      - ./volumes/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/start-nginx.sh:/etc/nginx/start-nginx.sh
    command: /bin/bash -c  "chmod +x /etc/nginx/*.sh && /etc/nginx/start-nginx.sh"